name: bamse-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - ruamel.yaml
  - cutadapt =2.10
  - libcurl =7.71.1
  - java-jdk =8.0.112
  - R =4.0.0
  - r-devtools
  - devtools:
    - git+https://github.com/benjjneb/dada2
