name: bamse-env
channels:
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - snakemake-minimal >=5.24.1
  - ruamel.yaml
  - cutadapt =2.10
  - libcurl =7.71.1
  - R =4.0.0
  - bioconductor-dada2
  - r-dplyr
  - r-devtools
  - r-optparse
  - perl-statistics-descriptive
  - gawk =5.1.0
  - vsearch
  - devtools:
     - git+https://github.com/tobiasgf/lulu
