name: bamse-env
channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - snakemake-minimal >=5.24.1
  - ruamel.yaml
  - cutadapt =2.10
  - R =4.0.0
  - devtools:
    - git+https://github.com/benjjneb/dada2
