name: bamse-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - ruamel.yaml
  - cutadapt =2.10
  - libcurl =7.71.1
  - R =4.0.0
  - bioconductor-dada2
  - perl-statistics-descriptive
