##
# General
##

bamsepath:
  /home/projects/ku-cbd/people/antalb/bamse
path:
  /home/projects/ku-cbd/people/antalb/bamse2

##
# Primer trimming
##
primer1:
  CTANGGGNNGCANCAG
primer2:
  GACTACNNGGGTATCTAAT

##
# Read filtering and trimming
##
maxN:
  0
maxEE: # After truncation, reads with higher than maxEE "expected errors" will be discarded. Expected errors are calculated from the nominal definition of the quality score: EE = sum(10^(-Q/10))
  Inf
truncQ: # Truncate reads at the first instance of a quality score less than or equal to truncQ.
  20
truncLen: # Truncate reads after truncLen bases. Reads shorter than this are discarded.
  0
